from bs4 import BeautifulSoup
import json

html = """
  <table id="example" class="display" cellspacing="0" width="100%" style="margin-top:50px;">
        
<thead><th> Character </th><th> Tier (beta) </th><th> Weight  </th><th> Air speed </th><th> Falling speed </th><th> Fast fall </th><th> Dash  </th><th> Run speed </th></tr></thead>
<tbody>
<tr><td> <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-BayonettaHeadSSBU.png">Bayonetta </td><td> D </td><td> 81  </td><td> 1,019 </td><td> 1,770 </td><td> 2,832 </td><td> 1,936 </td><td> 1,760 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-BowserHeadSSBU.png">Bowser </td><td> F </td><td> 135 </td><td> 1,155 </td><td> 1,770 </td><td> 2,832 </td><td> 2,255 </td><td> 1,971 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-BowserJrHeadSSBU.png">Bowser Jr. </td><td> G </td><td> 108 </td><td> 1,134 </td><td> 1,650 </td><td> 2,640 </td><td> 1,760 </td><td> 1,566 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-CaptainFalconHeadSSBU.png">Captain Falcon  </td><td> E </td><td> 104 </td><td> 1,218 </td><td> 1,865 </td><td> 2,984 </td><td> 1,980 </td><td> 2,552 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-CharizardHeadSSBU.png">Charizard </td><td> A </td><td> 116 </td><td> 1,103 </td><td> 1,520 </td><td> 2,432 </td><td> 2,288 </td><td> 2,200 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-ChromHeadSSBU.png">Chrom </td><td> B </td><td> 95  </td><td> 1,302 </td><td> 1,800 </td><td> 2,880 </td><td> 2,200 </td><td> 2,145 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-CloudHeadSSBU.png">Cloud </td><td> D </td><td> 100 </td><td> 1,155 </td><td> 1,680 </td><td> 2,688 </td><td> 2,145 </td><td> 2,167 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-CorrinHeadSSBU.png">Corrin </td><td> D </td><td> 98  </td><td> 1,019 </td><td> 1,650 </td><td> 2,640 </td><td> 1,892 </td><td> 1,595 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-DaisyHeadSSBU.png">Daisy </td><td> D </td><td> 89  </td><td> 1,029 </td><td> 1,190 </td><td> 1,904 </td><td> 1,826 </td><td> 1,595 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-DarkPitHeadSSBU.png">Dark Pit  </td><td> E </td><td> 96  </td><td> 0,935 </td><td> 1,480 </td><td> 2,368 </td><td> 2,090 </td><td> 1,828 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-DarkSamusHeadSSBU.png">Dark Samus  </td><td> G </td><td> 108 </td><td> 1,103 </td><td> 1,330 </td><td> 2,168 </td><td> 1,870 </td><td> 1,654 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-DiddyKongHeadSSBU.png">Diddy Kong  </td><td> A </td><td> 90  </td><td> 0,924 </td><td> 1,750 </td><td> 2,800 </td><td> 2,090 </td><td> 2,006 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-DonkeyKongHeadSSBU.png">Donkey Kong  </td><td> E </td><td> 127 </td><td> 1,208 </td><td> 1,630 </td><td> 2,608 </td><td> 2,090 </td><td> 1,873 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-DrMarioHeadSSBU.png">Dr. Mario </td><td> D </td><td> 98  </td><td> 0,924 </td><td> 1,500 </td><td> 2,400 </td><td> 1,936 </td><td> 1,397 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-DuckHuntHeadSSBU.png">Duck Hunt  </td><td> F </td><td> 86  </td><td> 1,155 </td><td> 1,650 </td><td> 2,640 </td><td> 1,760 </td><td> 1,793 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-FalcoHeadSSBU.png">Falco </td><td> A </td><td> 82  </td><td> 0,977 </td><td> 1,800 </td><td> 2,880 </td><td> 2,035 </td><td> 1,619 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-FoxHeadSSBU.png">Fox </td><td> D </td><td> 77  </td><td> 1,110 </td><td> 2,100 </td><td> 3,360 </td><td> 2,090 </td><td> 2,402 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-GanondorfHeadSSBU.png">Ganondorf </td><td> F </td><td> 118 </td><td> 0,830 </td><td> 1,650 </td><td> 2,640 </td><td> 1,870 </td><td> 1,340 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-GreninjaHeadSSBU.png">Greninja </td><td> D </td><td> 88  </td><td> 1,239 </td><td> 1,850 </td><td> 2,960 </td><td> 2,178 </td><td> 2,288 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-IceClimbersHeadSSBU.png">Ice Climbers  </td><td> G </td><td> 92  </td><td> 0,830 </td><td> 1,300 </td><td> 2,080 </td><td>   </td><td>   </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-IkeHeadSSBU.png">Ike </td><td> C </td><td> 107 </td><td> 1,134 </td><td> 1,650 </td><td> 2,640 </td><td> 1,815 </td><td> 1,507 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-IncineroarHeadSSBU.png">Incineroar </td><td> C </td><td> 116 </td><td> 0,880 </td><td> 1,760 </td><td> 2,816 </td><td> 1,716 </td><td> 1,180 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-InklingHeadSSBU.png">Inkling </td><td> C </td><td> 94  </td><td> 1,208 </td><td> 1,580 </td><td> 2,528 </td><td> 2,118 </td><td> 1,925 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-IsabelleHeadSSBU.png">Isabelle </td><td> F </td><td> 88  </td><td> 1,020 </td><td> 1,300 </td><td> 2,080 </td><td> 1,815 </td><td> 1,480 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-IvysaurHeadSSBU.png">Ivysaur </td><td> A </td><td> 96  </td><td> 0,998 </td><td> 1,380 </td><td> 2,208 </td><td> 1,903 </td><td> 1,595 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-JigglypuffHeadSSBU.png">Jigglypuff </td><td> E </td><td> 68  </td><td> 1,332 </td><td> 0,980 </td><td> 1,568 </td><td> 1,650 </td><td> 1,271 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-KenHeadSSBU.png">Ken </td><td> D </td><td> 103 </td><td> 1,120 </td><td> 1,600 </td><td> 2,240 </td><td> 1,936 </td><td> 1,760 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-KingDededeHeadSSBU.png">King Dedede  </td><td> F </td><td> 127 </td><td> 0,735 </td><td> 1,950 </td><td> 3,120 </td><td> 1,815 </td><td> 1,496 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-KingKRoolHeadSSBU.png">King K. Rool  </td><td> A </td><td> 133 </td><td> 0,945 </td><td> 1,700 </td><td> 2,720 </td><td> 1,936 </td><td> 1,485 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-KirbyHeadSSBU.png">Kirby </td><td> F </td><td> 79  </td><td> 0,840 </td><td> 1,230 </td><td> 1,968 </td><td> 1,900 </td><td> 1,727 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-LinkHeadSSBU.png">Link </td><td> G </td><td> 104 </td><td> 0,924 </td><td> 1,600 </td><td> 3,040 </td><td> 1,980 </td><td> 1,534 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-LittleMacHeadSSBU.png">Little Mac  </td><td> G </td><td> 87  </td><td> 1,208 </td><td> 1,950 </td><td> 3,120 </td><td> 2,365 </td><td> 2,464 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-LucarioHeadSSBU.png">Lucario </td><td> E </td><td> 92  </td><td> 1,281 </td><td> 1,680 </td><td> 2,688 </td><td> 2,255 </td><td> 1,705 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-LucasHeadSSBU.png">Lucas </td><td> E </td><td> 94  </td><td> 1,155 </td><td> 1,370 </td><td> 2,192 </td><td> 1,815 </td><td> 1,650 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-LucinaHeadSSBU.png">Lucina </td><td> C </td><td> 90  </td><td> 1,071 </td><td> 1,580 </td><td> 2,528 </td><td> 2,255 </td><td> 1,964 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-LuigiHeadSSBU.png">Luigi </td><td> C </td><td> 97  </td><td> 0,770 </td><td> 1,320 </td><td> 2,112 </td><td> 1,815 </td><td> 1,650 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-MarioHeadSSBU.png">Mario </td><td> E </td><td> 98  </td><td> 1,208 </td><td> 1,500 </td><td> 2,400 </td><td> 1,936 </td><td> 1,760 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-MarthHeadSSBU.png">Marth </td><td> C </td><td> 90  </td><td> 1,071 </td><td> 1,580 </td><td> 2,528 </td><td> 2,255 </td><td> 1,964 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-MegaManHeadSSBU.png">Mega Man  </td><td> G </td><td> 102 </td><td> 1,155 </td><td> 1,800 </td><td> 2,880 </td><td> 1,958 </td><td> 1,602 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-MetaKnightHeadSSBU.png">Meta Knight  </td><td> A </td><td> 80  </td><td> 1,040 </td><td> 1,660 </td><td> 2,656 </td><td> 2,211 </td><td> 2,090 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-MewtwoHeadSSBU.png">Mewtwo </td><td> B </td><td> 77  </td><td> 1,313 </td><td> 1,550 </td><td> 2,480 </td><td> 2,255 </td><td> 2,255 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-MiiBrawlerHeadSSBU.png">Mii Brawler  </td><td> G </td><td> 94  </td><td> 1,150 </td><td> 1,920 </td><td> 3,072 </td><td> 1,970 </td><td> 1,920 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-MiiGunnerHeadSSBU.png">Mii Gunner  </td><td> G </td><td> 104 </td><td> 0,930 </td><td> 1,450 </td><td> 2,320 </td><td> 1,613 </td><td> 1,370 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-MiiSwordfighterHeadSSBU.png">Mii Swordfighter  </td><td> G </td><td> 100 </td><td> 1,170 </td><td> 1,550 </td><td> 2,480 </td><td> 1,740 </td><td> 1,580 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-MrGame&WatchHeadSSBU.png">Mr. Game & Watch </td><td> F </td><td> 75  </td><td> 1,176 </td><td> 1,240 </td><td> 1,984 </td><td> 1,980 </td><td> 1,679 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-NanaHeadSSBU.png">Nana (Ice Climbers)  </td><td> G </td><td>   </td><td>   </td><td>   </td><td>   </td><td> 1,680 </td><td> 1,683 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-NessHeadSSBU.png">Ness </td><td> E </td><td> 94  </td><td> 1,007 </td><td> 1,310 </td><td> 2,096 </td><td> 1,826 </td><td> 1,609 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-OlimarHeadSSBU.png">Olimar </td><td> F </td><td> 79  </td><td> 0,861 </td><td> 1,350 </td><td> 2,160 </td><td> 1,606 </td><td> 1,617 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-Pac-ManHeadSSBU.png">Pac-Man </td><td> F </td><td> 95  </td><td> 1,092 </td><td> 1,350 </td><td> 2,160 </td><td> 1,870 </td><td> 1,672 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-PalutenaHeadSSBU.png">Palutena </td><td> F </td><td> 91  </td><td> 1,000 </td><td> 1,550 </td><td> 2,480 </td><td> 2,035 </td><td> 2,077 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-PeachHeadSSBU.png">Peach </td><td> D </td><td> 89  </td><td> 1,029 </td><td> 1,190 </td><td> 1,904 </td><td> 1,826 </td><td> 1,595 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-PichuHeadSSBU.png">Pichu </td><td> B </td><td> 62  </td><td> 1,029 </td><td> 1,900 </td><td> 2,500 </td><td> 1,980 </td><td> 1,892 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-PikachuHeadSSBU.png">Pikachu </td><td> B </td><td> 79  </td><td> 0,957 </td><td> 1,550 </td><td> 2,480 </td><td> 1,980 </td><td> 2,039 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-PiranhaPlantHeadSSBUWebsite.png">Piranha Plant </td><td> G </td><td> 94  </td><td> 1,000 </td><td> 0,000 </td><td> 0,000 </td><td> 1,820 </td><td> 1,120 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-PitHeadSSBU.png">Pit </td><td> E </td><td> 96  </td><td> 0,935 </td><td> 1,480 </td><td> 2,368 </td><td> 2,090 </td><td> 1,828 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-PopoHeadSSBU.png">Popo (Ice Climbers)  </td><td> G </td><td>   </td><td>   </td><td>   </td><td>   </td><td> 1,680 </td><td> 1,530 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-ROBHeadSSBU.png">R.O.B.  </td><td> E </td><td> 107 </td><td> 1,134 </td><td> 1,600 </td><td> 2,560 </td><td> 2,002 </td><td> 1,725 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-RichterHeadSSBU.png">Richter </td><td> A </td><td> 107 </td><td> 0,940 </td><td> 1,850 </td><td> 2,960 </td><td> 1,730 </td><td> 1,520 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-RidleyHeadSSBU.png">Ridley </td><td> F </td><td> 106 </td><td> 1,050 </td><td> 1,780 </td><td> 2,848 </td><td> 1,800 </td><td> 2,200 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-RobinHeadSSBU.png">Robin </td><td> F </td><td> 95  </td><td> 1,050 </td><td> 1,500 </td><td> 2,400 </td><td> 1,815 </td><td> 1,265 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-RosalinaHeadSSBU.png">Rosalina & Luma  </td><td> F </td><td> 82  </td><td> 1,050 </td><td> 1,200 </td><td> 1,920 </td><td> 2,035 </td><td> 1,795 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-RoyHeadSSBU.png">Roy </td><td> B </td><td> 95  </td><td> 1,302 </td><td> 1,800 </td><td> 2,880 </td><td> 2,200 </td><td> 2,145 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-RyuHeadSSBU.png">Ryu </td><td> D </td><td> 103 </td><td> 1,120 </td><td> 1,600 </td><td> 2,240 </td><td> 1,760 </td><td> 1,600 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-SamusHeadSSBU.png">Samus </td><td> G </td><td> 108 </td><td> 1,103 </td><td> 1,330 </td><td> 2,168 </td><td> 1,870 </td><td> 1,654 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-SheikHeadSSBU.png">Sheik </td><td> D </td><td> 78  </td><td> 1,155 </td><td> 1,750 </td><td> 2,800 </td><td> 2,178 </td><td> 2,420 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-ShulkHeadSSBU.png">Shulk </td><td> C </td><td> 97  </td><td> 1,113 </td><td> 1,580 </td><td> 2,528 </td><td> 1,870 </td><td> 1,672 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-SimonHeadSSBU.png">Simon </td><td> A </td><td> 107 </td><td> 0,940 </td><td> 1,850 </td><td> 2,960 </td><td> 1,730 </td><td> 1,520 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-SnakeHeadSSBU.png">Snake </td><td> D </td><td> 106 </td><td> 0,987 </td><td> 1,730 </td><td> 2,768 </td><td> 1,760 </td><td> 1,595 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-SonicHeadSSBU.png">Sonic </td><td> D </td><td> 86  </td><td> 1,208 </td><td> 1,650 </td><td> 2,640 </td><td> 2,310 </td><td> 3,850 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-SquirtleHeadSSBU.png">Squirtle </td><td> A </td><td> 75  </td><td> 1,010 </td><td> 1,350 </td><td> 2,160 </td><td> 1,936 </td><td> 1,760 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-ToonLinkHeadSSBU.png">Toon Link  </td><td> D </td><td> 91  </td><td> 1,050 </td><td> 1,380 </td><td> 2,208 </td><td> 1,914 </td><td> 1,906 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-VillagerHeadSSBU.png">Villager </td><td> F </td><td> 92  </td><td> 0,987 </td><td> 1,320 </td><td> 2,112 </td><td> 1,815 </td><td> 1,397 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-WarioHeadSSBU.png">Wario </td><td> F </td><td> 107 </td><td> 1,271 </td><td> 1,610 </td><td> 2,576 </td><td> 1,837 </td><td> 1,650 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-WiiFitTrainerHeadSSBU.png">Wii Fit Trainer </td><td> F </td><td> 96  </td><td> 1,019 </td><td> 1,300 </td><td> 2,080 </td><td> 2,024 </td><td> 1,866 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-WolfHeadSSBU.png">Wolf </td><td> D </td><td> 92  </td><td> 1,281 </td><td> 1,800 </td><td> 2,880 </td><td> 2,090 </td><td> 1,540 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-YoshiHeadSSBU.png">Yoshi </td><td> B </td><td> 104 </td><td> 1,344 </td><td> 1,290 </td><td> 2,064 </td><td> 1,980 </td><td> 2,046 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-YoungLinkHeadSSBU.png">Young Link  </td><td> D </td><td> 88  </td><td> 0,966 </td><td> 1,800 </td><td> 2,880 </td><td> 2,090 </td><td> 1,749 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-ZeldaHeadSSBU.png">Zelda </td><td> F </td><td> 85  </td><td> 1,092 </td><td> 1,350 </td><td> 2,160 </td><td> 1,958 </td><td> 1,430 </td></tr>
<tr><td>  <img style="margin-right:5px; margin-bottom:-10px; margin-top:-13px; vertical-align:middle" width="20" src="https://www.unitstatistics.com/img/ssbu/20px-ZeroSuitSamusHeadSSBU.png">Zero Suit Samus </td><td> E </td><td> 80  </td><td> 1,260 </td><td> 1,700 </td><td> 2,720 </td><td> 2,420 </td><td> 2,310 </td></tr></tbody></table>


"""

soup = BeautifulSoup(html)
table = soup.find('table')
# print(table)

# The first tr contains the field names.
headings = [th.get_text().strip() for th in table.find("thead").find_all("th")]

# print(headings)

table = soup.find('tbody')

datasets = []
for row in table.find_all("tr")[0:]:
    dataset = dict(zip(headings, (td.get_text() for td in row.find_all("td"))))
    datasets.append(dataset)

# print(datasets)

with open('data.json', 'w') as f:
    json.dump(datasets, f)